"""empty message

Revision ID: 1ccd25d2570f
Revises: 
Create Date: 2019-08-30 15:20:56.221634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ccd25d2570f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('photo', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('maxPax', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher', sa.String(length=128), nullable=True),
    sa.Column('dateUsed', sa.Date(), nullable=True), 
    sa.Column('maxPax', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('isUploaded', sa.Integer(), nullable=True),
    sa.Column('usedPax', sa.Integer(), nullable=True),
    sa.Column('events_id', sa.Integer(), nullable=True),
    sa.Column('numOfDays', sa.Integer(), nullable=True),
    sa.Column('dayUsed', sa.Integer(), nullable=True),
    sa.Column('events_day', sa.Date(), nullable=True),  
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], ondelete="CASCADE" ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_email'), 'vouchers', ['email'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vouchers_id', sa.Integer(), nullable=True),
    sa.Column('pax', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vouchers_id'], ['vouchers.id'], ondelete="CASCADE" ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vouchers_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['vouchers_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('claims')
    op.drop_index(op.f('ix_vouchers_email'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_table('events')
    # ### end Alembic commands ###
